### ISSUE TITLE
Clarify download location

### ISSUE THREAD

**Issue by mroswell** [mishterk/wp-tailwindcss-theme-boilerplate#22]
"Clone into an empty theme directory" is a little bit confusing. Does that mean that no other themes should be present at this level? If I'm doing local development do I create a subdirectory here?
~/Local Sites/safer-or-toxic/app/public/wp-content/themes

Or maybe I just run git clone in that directory (though it isn't empty)

**Comment by mroswell** [comment]
Ooh, very helpful video at https://philkurth.com.au/articles/wordpress-theme-using-tailwind-css/

I like that you showed where to start... and that you showed how to create a different theme name. 
Might be helpful to update README to say 
```
cd into theme directory (often ../wp-content/themes)
% git clone https://github.com/mishterk/wp-tailwindcss-theme-boilerplate.git <my_theme_name>
(be sure to substitute your own theme name)
```

I'm excited to find this project! Working my way through the video now.

**Comment by mishterk** [comment]
Howdy. Just updated the readme to clarify this — thanks for suggesting. 
See https://github.com/mishterk/wp-tailwindcss-theme-boilerplate/commit/e8b9999e4d686fecb617749a32c13e53fd7b2d56.
