### ISSUE TITLE
require('./local') prevents webpack build in a non-prod remote build

### ISSUE THREAD

**Issue by tomrainedotcom** [mishterk/wp-tailwindcss-theme-boilerplate#5]
Been looking for something like this to get a project off the ground but came across a little speed bump when trying to build on pipelines and git ftp the project to remote server. Webpack would fail when trying to load `./local` so I rapped all the local proxy stuff in an fs.stat
```text/javascript
fs.stat('./local', function(access) {
    if (access.errno >= 0) {
        const local = require('./local');
        if (local.proxy) {
            mix.browserSync({
                proxy: local.proxy,
                injectChanges: true,
                open: false,
                files: [
                    'build/**/*.{css,js}',
                    'templates/**/*.php'
                ]
            });
        }
    }
});
```

Probably not the cleanest thing but works a charm

**Comment by EltonWhybrow** [comment]
Many thanks, this saved me some time. The only issue too so pretty lucky.

**Comment by mishterk** [comment]
Thanks @tomrainedotcom.

I've just pushed a commit that moves this out into a separate file to keep the main webpack.mix.js file as simple as possible. Have a look at https://github.com/mishterk/wp-tailwindcss-theme-boilerplate/commit/140fb7152d3ac25011d3127283b7d63babc95f6d.

Working OK for me locally when the file isn't present. If you try this and it doesn't work for you, could you let me know?
